#server:
#  port: 8770
#spring:
#  application:
#    name: nacosgateway
#  cloud:
#    nacos:
#      #discovery:
#       # server-addr: 49.235.114.120:8848
#      config:
#        server-addr: 49.235.114.120:8848
#        dataId: gateway-router
#        group: DEFAULT_GROUP
#    gateway:
#      discovery:
#        locator:
#          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
#         lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
#eureka:
# client:
#   serviceUrl:
#     defaultZone: http://localhost:8761/eureka