#server:
#  port: 8770
#spring:
#  application:
#    name: eurekagateway
#  cloud:
#    gateway:
#     discovery:
#       locator:
#         enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
#     routes:
#       - id: service-provider-get # 路由的id,没有规定规则但要求唯一,建议配合服务名
#         #匹配后提供服务的路由地址
#         uri: http://localhost:8763
#         order: 1
#         predicates:
#           - Path=/hi # **：通配符 ；断言，路径相匹配的进行路由
#       - id: service-provider-get # 路由的id,没有规定规则但要求唯一,建议配合服务名
#         #匹配后提供服务的路由地址
#         uri: lb://eurekaclient
#         order: 0
#         predicates:
#           - Path=/hi # **：通配符 ；断言，路径相匹配的进行路由


#eureka:
# client:
#   serviceUrl:
#     defaultZone: http://localhost:8761/eureka