spring:
  application:
    name: turbine
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

turbine:
  aggregator:
    clusterConfig: default
  appConfig: resttemplateribbon,feignribbon
  clusterNameExpression: new String("default")

